const TOPIC_ID = 'chapter-3-using-liferafts'

const CFR_SOURCE = '46 CFR Subpart 160.151 — Inflatable Liferafts; existing repository copy Document(6).PDF.pdf, summarized in docs/vinci-2026-07-20-chapter-3-source-readiness-and-question-audit.md'
const WORKSHEET_SOURCE = 'Liferaft parts worksheet 2026-07-07_063330-1.jpg with 23-item answer key; summarized in docs/vinci-2026-07-20-chapter-3-source-readiness-and-question-audit.md'

function makeQuestion({ id, prompt, correct, distractors, explanation, difficulty = 'medium', sourceReference = CFR_SOURCE, verificationStatus = 'source-backed-study' }) {
  return {
    id,
    topicId: TOPIC_ID,
    prompt,
    choices: [
      { id: 'a', text: correct },
      ...distractors.map((text, index) => ({
        id: String.fromCharCode(98 + index),
        text,
        misconception: `This does not match the cited Chapter 3 source for this item.`,
      })),
    ],
    correctChoiceId: 'a',
    difficulty,
    hints: ['Focus on the exact liferaft equipment, component, or regulatory requirement named in the source.'],
    explanation,
    sourceReference,
    verificationStatus,
  }
}

const requiredEquipment = [
  ['heaving-line', 'Heaving line', ['Boat hook', 'Emergency towing hawser', 'Mooring chain']],
  ['jackknife', 'Jackknife', ['Marlinspike', 'Bolt cutter', 'Rigging axe']],
  ['bailer', 'Bailer', ['Bilge pump motor', 'Fire bucket only', 'Deck wash hose']],
  ['sponge', 'Sponge', ['Chamois cloth only', 'Mop bucket', 'Portable fan']],
  ['sea-anchor', 'Sea anchor', ['Ship anchor chain', 'Davit brake', 'Steering oar only']],
  ['paddles', 'Paddles', ['Propeller shaft', 'Fleming gear', 'Boat davit handles']],
  ['tin-opener', 'Tin opener', ['Can-sealing tool', 'Bottle corker', 'Galley cleaver']],
  ['first-aid-kit', 'First-aid kit', ['Medical oxygen cylinder only', 'Stretcher only', 'Surgical instrument chest']],
  ['whistle', 'Whistle', ['Ship horn', 'Engine-room bell', 'Bosun chair']],
  ['rocket-parachute-flare', 'Rocket parachute flare', ['Pilot ladder light', 'Masthead lamp', 'Cabin lantern only']],
  ['hand-flare', 'Hand flare', ['Signal flag only', 'Searchlight bulb', 'Engine starting torch']],
  ['smoke-signal', 'Buoyant smoke signal', ['Smoke hood', 'Engine exhaust marker', 'Paint marker']],
  ['electric-torch', 'Electric torch', ['Deck floodlight fixture', 'Cabin fan', 'Battery charger only']],
  ['radar-reflector', 'Radar reflector', ['Magnetic compass repeater', 'Echo sounder', 'EPIRB bracket only']],
  ['signal-mirror', 'Signaling mirror', ['Inspection mirror', 'Shaving mirror', 'Lens cover']],
  ['lifesaving-signals-card', 'Lifesaving-signals card', ['Cargo plan', 'Engine log', 'Crew payroll sheet']],
  ['fishing-tackle', 'Fishing tackle', ['Harpoon gun', 'Commercial trawl net', 'Diving spear gun']],
  ['food-rations', 'Food rations', ['Fresh galley meals', 'Salt tablets only', 'Cooking oil only']],
  ['drinking-water', 'Drinking water or an approved desalting arrangement', ['Seawater storage only', 'Engine coolant', 'Ballast water']],
  ['drinking-cup', 'Drinking cup', ['Galley tray', 'Measuring beaker only', 'Fuel funnel']],
  ['anti-seasickness', 'Anti-seasickness medicine', ['Sleeping pills only', 'Antibiotics only', 'Pain medicine only']],
  ['survival-instructions', 'Waterproof survival instructions in English, suspended from a canopy arch tube', ['Loose paper stored under the floor', 'Instructions painted only on the container exterior', 'A radio message with no written copy']],
  ['immediate-action', 'Instructions for immediate action', ['Ship maintenance schedule', 'Port arrival checklist', 'Cargo loading sequence']],
]

const equipmentQuestions = requiredEquipment.map(([slug, correct, distractors], index) => makeQuestion({
  id: `q-ch3-cfr-equip-${slug}`,
  prompt: `Which item is explicitly included in the federal required-equipment list for an inflatable liferaft?`,
  correct,
  distractors,
  difficulty: index < 8 ? 'easy' : 'medium',
  explanation: `${correct} is explicitly named in 46 CFR §160.151-21 as required inflatable-liferaft equipment.`,
}))

const worksheetParts = [
  [2, 'Equipment bags'],
  [4, 'Pressure relief valve'],
  [5, 'Heaving line'],
  [8, 'Rainwater catchment tube assembly'],
  [9, 'Righting strap'],
  [10, 'CO2 inflation system'],
  [11, 'Deflation plug'],
  [14, 'Buoyancy tube'],
  [16, 'Operating cord / sea painter'],
  [21, 'Boarding ladder'],
]

const allPartNames = worksheetParts.map(([, name]) => name)
const diagramQuestions = worksheetParts.flatMap(([number, name], index) => {
  const distractorNames = [
    allPartNames[(index + 1) % allPartNames.length],
    allPartNames[(index + 3) % allPartNames.length],
    allPartNames[(index + 6) % allPartNames.length],
  ]
  const distractorNumbers = [
    worksheetParts[(index + 1) % worksheetParts.length][0],
    worksheetParts[(index + 3) % worksheetParts.length][0],
    worksheetParts[(index + 6) % worksheetParts.length][0],
  ].map(String)
  return [
    makeQuestion({
      id: `q-ch3-visual-part-${number}-name`,
      prompt: `On the 23-item liferaft worksheet, what component is identified as number ${number}?`,
      correct: name,
      distractors: distractorNames,
      difficulty: 'medium',
      explanation: `The worksheet answer key identifies number ${number} as the ${name}.`,
      sourceReference: WORKSHEET_SOURCE,
      verificationStatus: 'visual-study',
    }),
    makeQuestion({
      id: `q-ch3-visual-part-${number}-number`,
      prompt: `On the 23-item liferaft worksheet, which number identifies the ${name}?`,
      correct: String(number),
      distractors: distractorNumbers,
      difficulty: 'hard',
      explanation: `The worksheet answer key assigns the ${name} to number ${number}.`,
      sourceReference: WORKSHEET_SOURCE,
      verificationStatus: 'visual-study',
    }),
  ]
})

const regulationQuestions = [
  makeQuestion({
    id: 'q-ch3-cfr-painter-environment',
    prompt: 'What environmental deterioration must the liferaft painter system be designed to resist?',
    correct: 'Sunlight and salt-spray deterioration, along with water absorption',
    distractors: ['Heat from the engine room only', 'Freshwater exposure only', 'Mechanical wear only, with no environmental requirement'],
    explanation: 'The painter-system requirement specifically addresses sunlight, salt spray, and water absorption.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-inflation-trigger',
    prompt: 'What action starts inflation in the linked painter-and-cylinder system?',
    correct: 'Pulling the painter',
    distractors: ['Opening the canopy lamp housing', 'Deploying the sea anchor', 'Removing the first-aid kit'],
    explanation: 'The painter and inflation cylinders are linked so pulling the painter starts inflation.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-inflation-force',
    prompt: 'What is the maximum pull force identified for starting inflation through the painter system?',
    correct: '150 N, approximately 34 lb',
    distractors: ['15 N, approximately 3.4 lb', '500 N, approximately 112 lb', '1,500 N, approximately 337 lb'],
    difficulty: 'hard',
    explanation: 'The source identifies a maximum activation pull of 150 N, approximately 34 lb.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-boarding-ladder-footing',
    prompt: 'What must liferaft boarding-ladder steps provide?',
    correct: 'A suitable foothold',
    distractors: ['A hand-operated inflation pump', 'A place to mount the radar reflector', 'A storage location for food rations'],
    explanation: 'The boarding-ladder requirement is framed around providing a suitable foothold.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-container-seal',
    prompt: 'What feature must the liferaft container include to show whether it has been disturbed?',
    correct: 'A tamper-evident telltale seal-and-wire',
    distractors: ['A painted inspection stripe only', 'A padlock requiring a key', 'A pressure gauge visible from the bridge'],
    explanation: 'The container requirement includes a tamper-evident telltale seal-and-wire.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-container-break-free',
    prompt: 'What must happen to the liferaft as inflation begins while it is still associated with its container?',
    correct: 'It must be designed to break free of the container',
    distractors: ['It must remain locked inside the container', 'The container must fill with water first', 'The canopy must be removed before inflation'],
    explanation: 'The design must allow the raft to break free of the container when inflation begins.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-survival-instructions-location',
    prompt: 'Where are the waterproof survival instructions required to be suspended?',
    correct: 'From a canopy arch tube',
    distractors: ['Under the inflatable floor', 'Inside the sea anchor', 'On the outside of the painter line'],
    explanation: 'The regulation specifies waterproof English-language survival instructions suspended from a canopy arch tube.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-survival-instructions-language',
    prompt: 'In what language must the required survival instructions be provided under the cited regulation?',
    correct: 'English',
    distractors: ['Any language chosen by the manufacturer', 'Only the vessel flag-state language', 'No written language is required'],
    explanation: 'The cited federal requirement specifies waterproof survival instructions in English.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-maintenance-monthly',
    prompt: 'What recurring shipboard check is identified for an inflatable liferaft?',
    correct: 'A monthly external visual inspection',
    distractors: ['A daily full inflation test', 'A weekly sea trial', 'An annual onboard destructive test'],
    explanation: 'The maintenance section identifies a monthly external visual inspection checklist.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-servicing-location',
    prompt: 'Where must periodic liferaft servicing be performed?',
    correct: 'At an approved servicing facility',
    distractors: ['Anywhere aboard ship without approval', 'Only at the vessel owner’s office', 'At any marina selected by the crew'],
    explanation: 'Periodic servicing is assigned to an approved servicing facility.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-maintenance-log',
    prompt: 'What record must be maintained for liferaft upkeep?',
    correct: 'A maintenance log',
    distractors: ['A cargo manifest', 'A bridge bell book only', 'A passenger meal log'],
    explanation: 'The maintenance section calls for a maintenance log.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-ballast-purpose',
    prompt: 'What is the primary purpose of water-filled underside ballast appendages on an inflatable liferaft?',
    correct: 'To improve stability in the water',
    distractors: ['To store drinking water', 'To inflate the canopy', 'To hold signaling flares'],
    explanation: 'The cited design provisions address underside water-filled appendages as stability features.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-ballast-location',
    prompt: 'Where are the water-filled stability appendages located?',
    correct: 'On the underside of the liferaft',
    distractors: ['On top of the canopy', 'Inside the equipment bags', 'Along the painter line'],
    explanation: 'The regulation describes water-filled appendages deployed beneath the raft.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-ramp-rating-kg',
    prompt: 'For what occupant mass must the boarding ramp be rated?',
    correct: '100 kg',
    distractors: ['50 kg', '75 kg', '150 kg'],
    difficulty: 'hard',
    explanation: 'The boarding ramp is rated for a 100 kg occupant.',
  }),
  makeQuestion({
    id: 'q-ch3-cfr-ramp-rating-lb',
    prompt: 'What approximate pound rating corresponds to the boarding-ramp occupant requirement?',
    correct: '220 lb',
    distractors: ['110 lb', '165 lb', '330 lb'],
    difficulty: 'hard',
    explanation: 'The cited requirement gives 100 kg, approximately 220 lb.',
  }),
  makeQuestion({
    id: 'q-ch3-scenario-inflation-start',
    prompt: 'A crew member throws the liferaft container overboard but never pulls the painter. Which key inflation step has not occurred?',
    correct: 'The linked painter-trigger action that starts inflation',
    distractors: ['Opening the first-aid kit', 'Deploying the fishing tackle', 'Suspending the survival instructions'],
    difficulty: 'hard',
    explanation: 'Under the cited system, pulling the painter initiates inflation.',
  }),
  makeQuestion({
    id: 'q-ch3-scenario-container-tamper',
    prompt: 'During inspection, the telltale seal-and-wire on a liferaft container is broken. What does that feature primarily indicate?',
    correct: 'The container may have been opened or disturbed',
    distractors: ['The sea anchor is deployed', 'The canopy lamp battery is charged', 'The raft has passed periodic servicing'],
    difficulty: 'hard',
    explanation: 'The seal-and-wire is a tamper-evident feature, not an operating-status indicator.',
  }),
  makeQuestion({
    id: 'q-ch3-scenario-monthly-vs-service',
    prompt: 'Which task belongs to routine shipboard monthly inspection rather than periodic approved-facility servicing?',
    correct: 'External visual inspection using the checklist',
    distractors: ['Full periodic servicing at an approved facility', 'Manufacturer-level repair', 'Replacement of all inflation cylinders regardless of condition'],
    difficulty: 'hard',
    explanation: 'Monthly external visual inspection and periodic facility servicing are separate maintenance layers.',
  }),
  makeQuestion({
    id: 'q-ch3-compare-heaving-painter',
    prompt: 'Which line is directly linked to starting the raft’s inflation system?',
    correct: 'The operating cord / sea painter',
    distractors: ['The heaving line', 'The internal lifeline', 'The towing bridle'],
    difficulty: 'hard',
    explanation: 'The painter is linked to inflation; the heaving line serves a different purpose.',
    sourceReference: `${CFR_SOURCE}; ${WORKSHEET_SOURCE}`,
  }),
  makeQuestion({
    id: 'q-ch3-compare-righting-boarding',
    prompt: 'Which worksheet component is intended for restoring an overturned raft rather than climbing into it?',
    correct: 'Righting strap',
    distractors: ['Boarding ladder', 'Equipment bags', 'Rainwater catchment tube assembly'],
    difficulty: 'hard',
    explanation: 'The righting strap and boarding ladder are separate labeled components with different purposes.',
    sourceReference: WORKSHEET_SOURCE,
    verificationStatus: 'visual-study',
  }),
  makeQuestion({
    id: 'q-ch3-compare-relief-deflation',
    prompt: 'Which pair consists of two separate air-management components identified on the worksheet?',
    correct: 'Pressure relief valve and deflation plug',
    distractors: ['Heaving line and boarding ladder', 'Equipment bags and righting strap', 'Rainwater catchment tube and sea painter'],
    difficulty: 'hard',
    explanation: 'The worksheet identifies the pressure relief valve and deflation plug as distinct components.',
    sourceReference: WORKSHEET_SOURCE,
    verificationStatus: 'visual-study',
  }),
]

export const chapter3Questions = [
  ...equipmentQuestions,
  ...diagramQuestions,
  ...regulationQuestions,
]

export const chapter3Learn = {
  concept: 'Chapter 3 now includes source-backed instruction built from 46 CFR Subpart 160.151 and a 23-item liferaft-parts worksheet. The actual Chapter 3 manual pages remain unavailable, so this material is intentionally labeled as federal-regulation or visual-study content rather than course-manual-verified content.',
  keyPoints: [
    {
      title: 'Liferafts and Required Equipment',
      explanation: 'Federal regulations identify a broad equipment package intended to support signaling, first aid, water and food management, navigation support, immediate survival actions, and basic raft operation.',
      keyFacts: requiredEquipment.map(([, name]) => name),
      confusionTraps: ['Do not treat every useful maritime tool as required liferaft equipment.', 'A required equipment list is different from the labeled structural parts of the raft itself.'],
      examWatchFor: ['Questions may ask which item is required, which item is not, or which category a required item supports.'],
      sourceReferences: [{ file: 'Document(6).PDF.pdf', note: '46 CFR §160.151-21 equipment list' }],
      confidence: 'high',
    },
    {
      title: 'Liferaft Size',
      explanation: 'The available sources in this repository do not provide the missing course-manual treatment of liferaft size. No new size rule is added here beyond the existing live bank.',
      keyFacts: ['Actual Chapter 3 manual pages 35-88 remain missing.'],
      confusionTraps: ['Do not infer course-specific capacity rules from unrelated lifeboat requirements.'],
      examWatchFor: ['Use only the existing verified question bank for size facts until the manual pages are supplied.'],
      confidence: 'limited',
    },
    {
      title: 'Liferaft Stowage',
      explanation: 'The federal source supports container-integrity concepts, including a tamper-evident telltale seal-and-wire and a design that allows the raft to break free when inflation begins.',
      keyFacts: ['Container includes a tamper-evident telltale seal-and-wire.', 'The raft must break free of the container as inflation begins.'],
      confusionTraps: ['The telltale seal indicates possible disturbance; it does not prove the raft is serviceable.', 'The container is not intended to remain locked around an inflating raft.'],
      examWatchFor: ['Distinguish stowage integrity from deployment operation.'],
      sourceReferences: [{ file: 'Document(6).PDF.pdf', note: '46 CFR §160.151-17 container provisions' }],
      confidence: 'high',
    },
    {
      title: 'Liferaft Design',
      explanation: 'The worksheet identifies major structural and operating parts, while the regulation adds stability appendages and boarding-ramp requirements.',
      keyFacts: ['Buoyancy tube, pressure relief valve, deflation plug, CO2 inflation system, and inflatable floor are distinct parts.', 'Water-filled underside appendages improve stability.', 'The boarding ramp is rated for a 100 kg / 220 lb occupant.'],
      confusionTraps: ['Pressure relief and deliberate deflation are not the same function.', 'Ballast appendages are stability devices, not drinking-water storage.'],
      examWatchFor: ['Expect component-identification and function-comparison questions.'],
      sourceReferences: [{ file: '2026-07-07_063330-1.jpg', note: '23-item worksheet answer key' }, { file: 'Document(6).PDF.pdf', note: '46 CFR §160.151-1 design provisions' }],
      confidence: 'high',
    },
    {
      title: 'Liferaft Markings',
      explanation: 'The available Chapter 3 source set does not contain enough course-manual detail to expand markings safely. Existing live questions remain available, but no new marking claims are introduced here.',
      keyFacts: ['Course-manual pages remain missing.'],
      confusionTraps: ['Do not transfer lifeboat marking rules automatically to liferafts.'],
      examWatchFor: ['Treat marking questions carefully until the source gap is closed.'],
      confidence: 'limited',
    },
    {
      title: 'Liferaft Launching Procedures / Instructions',
      explanation: 'The painter is operationally linked to the inflation cylinders. Pulling it with no more than 150 N / 34 lb force starts inflation.',
      keyFacts: ['Pulling the painter starts inflation.', 'The activation-force ceiling is 150 N, approximately 34 lb.', 'The raft must break free of its container as inflation begins.'],
      confusionTraps: ['Throwing the container overboard is not the same as completing the painter-trigger step.', 'The heaving line is not the inflation trigger.'],
      examWatchFor: ['Sequence questions often separate launching, painter pull, inflation, and container break-free.'],
      sourceReferences: [{ file: 'Document(6).PDF.pdf', note: '46 CFR §160.151-17(k)-(p)' }],
      confidence: 'high',
    },
    {
      title: 'Davit Launching',
      explanation: 'The current repository sources do not provide enough unused Chapter 3-specific material to expand davit launching without risking unsupported claims.',
      keyFacts: ['No new davit-launching claims are added in this expansion.'],
      confusionTraps: ['Do not substitute lifeboat davit procedures for liferaft procedures.'],
      examWatchFor: ['Use existing live questions only until the manual pages are supplied.'],
      confidence: 'limited',
    },
    {
      title: 'Automatic Launching',
      explanation: 'The painter-trigger and container break-free requirements explain key parts of deployment, but the missing manual pages prevent a full course-specific automatic-launching lesson.',
      keyFacts: ['Painter pull starts inflation.', 'The raft must break free of its container as inflation begins.'],
      confusionTraps: ['Automatic release concepts and the manual act of pulling the painter are not interchangeable.'],
      examWatchFor: ['Read carefully for the exact stage of deployment being tested.'],
      confidence: 'moderate',
    },
    {
      title: 'Manual Launching',
      explanation: 'The source-backed sequence emphasizes deployment of the container, control through the painter, and inflation initiated by pulling the painter.',
      keyFacts: ['The sea painter / operating cord is distinct from the heaving line.', 'Pulling the painter initiates inflation.'],
      confusionTraps: ['Do not cut or release the controlling line before the raft is properly inflated and managed.'],
      examWatchFor: ['Line-identification questions are common traps.'],
      sourceReferences: [{ file: 'Document(6).PDF.pdf', note: 'Painter and inflation provisions' }, { file: '2026-07-07_063330-1.jpg', note: 'Operating cord / sea painter labeled #16' }],
      confidence: 'high',
    },
    {
      title: 'Righting the Capsized Raft',
      explanation: 'The worksheet identifies a dedicated righting strap as a separate component from the boarding ladder and towing gear.',
      keyFacts: ['Righting strap is worksheet item #9.', 'Boarding ladder is worksheet item #21.'],
      confusionTraps: ['A boarding ladder is for entry; the righting strap is associated with restoring an overturned raft.'],
      examWatchFor: ['Expect diagram-number and function-comparison questions.'],
      sourceReferences: [{ file: '2026-07-07_063330-1.jpg', note: 'Righting strap #9 and boarding ladder #21' }],
      confidence: 'high',
    },
    {
      title: 'Boarding the Liferaft',
      explanation: 'The federal requirement focuses on a suitable foothold for boarding-ladder steps and a boarding ramp rated for a 100 kg / 220 lb occupant.',
      keyFacts: ['Boarding-ladder steps must provide a suitable foothold.', 'Boarding ramp rating: 100 kg / 220 lb occupant.'],
      confusionTraps: ['The ladder and ramp are related boarding aids but not the same component.'],
      examWatchFor: ['Watch for the exact occupant rating and component name.'],
      sourceReferences: [{ file: 'Document(6).PDF.pdf', note: '46 CFR §160.151-17(n) and §160.151-1' }],
      confidence: 'high',
    },
    {
      title: 'Assisting Injured People',
      explanation: 'The current unused Chapter 3 sources confirm boarding aids and required first-aid equipment, but they do not provide enough course-manual detail for a full casualty-handling procedure.',
      keyFacts: ['A first-aid kit is required equipment.', 'Boarding steps must provide suitable footing.', 'The boarding ramp is rated for 100 kg / 220 lb.'],
      confusionTraps: ['Equipment availability is not the same as a complete casualty-transfer procedure.'],
      examWatchFor: ['Use only source-supported statements when evaluating an injured-person scenario.'],
      confidence: 'moderate',
    },
  ],
}

export const chapter3DrillSets = [
  { id: 'ch3-required-equipment', title: 'Required Liferaft Equipment', questionIds: equipmentQuestions.map((q) => q.id) },
  { id: 'ch3-diagram-numbers', title: 'Liferaft Diagram Numbers', questionIds: diagramQuestions.filter((q) => q.id.endsWith('-number')).map((q) => q.id) },
  { id: 'ch3-diagram-names', title: 'Liferaft Diagram Names', questionIds: diagramQuestions.filter((q) => q.id.endsWith('-name')).map((q) => q.id) },
  { id: 'ch3-painter-inflation', title: 'Painter and Inflation', questionIds: regulationQuestions.filter((q) => /painter|inflation|container/.test(q.id)).map((q) => q.id) },
  { id: 'ch3-maintenance', title: 'Inspection and Maintenance', questionIds: regulationQuestions.filter((q) => /maintenance|monthly|servicing/.test(q.id)).map((q) => q.id) },
  { id: 'ch3-stability-boarding', title: 'Stability and Boarding', questionIds: regulationQuestions.filter((q) => /ballast|ramp|boarding|righting/.test(q.id)).map((q) => q.id) },
  { id: 'ch3-lines-and-components', title: 'Lines and Components', questionIds: regulationQuestions.filter((q) => /compare|scenario/.test(q.id)).map((q) => q.id) },
]
